#%RAML 1.0 DataType

type: object
properties:
  Code: string
  Name: string
  Continent: string
  Region: string
  SurfaceArea: number
  IndepYear?: integer
  Population: integer
  LifeExpectancy?: number
  GNP?: number
  GNPOld?: number
  LocalName: string
  GovernmentForm: string
  HeadOfState?: string
  Capital?: integer
  Code2: string
