[
  {
    "ID": 3793,
    "Name": "Washington",
    "CountryCode": "USA",
    "District": "District of Columbia",
    "Population": 633427
  },
  {
    "ID": 1101,
    "Name": "São Paulo",
    "CountryCode": "BRA",
    "District": "São Paulo",
    "Population": 12106920
  }
]
