[
  {
    "CountryCode": "BRA",
    "Language": "Portuguese",
    "IsOfficial": true,
    "Percentage": 98.1
  },
  {
    "CountryCode": "USA",
    "Language": "English",
    "IsOfficial": true,
    "Percentage": 82.1
  }
]
