[
  {
    "Code": "BRA",
    "Name": "Brazil",
    "Continent": "South America",
    "Region": "South America",
    "SurfaceArea": 8515767,
    "IndepYear": 1822,
    "Population": 210147125,
    "LifeExpectancy": 75.4,
    "GNP": 1869000,
    "GNPOld": 1836000,
    "LocalName": "Brasil",
    "GovernmentForm": "Federal Republic",
    "HeadOfState": "Jair Bolsonaro",
    "Capital": 211,
    "Code2": "BR"
  },
  {
    "Code": "USA",
    "Name": "United States",
    "Continent": "North America",
    "Region": "North America",
    "SurfaceArea": 9372610,
    "IndepYear": 1776,
    "Population": 331002651,
    "LifeExpectancy": 78.9,
    "GNP": 21430000,
    "GNPOld": 21000000,
    "LocalName": "United States",
    "GovernmentForm": "Federal Republic",
    "HeadOfState": "Joe Biden",
    "Capital": 3793,
    "Code2": "US"
  }
]
